FROM node:6.9.4

RUN mkdir -p /app
RUN npm install -g yarn
WORKDIR /app

COPY package.json /app
COPY yarn.lock /app
RUN yarn install

COPY . /app

RUN npm run build

EXPOSE 80
CMD ["npm", "run", "start"]