version: "2"
services:
  boilerplate:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: boilerplate
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3001:3001"
    command: npm run dev