version: "2"
networks:
  default:
    external:
      name: front
services:
  boilerplate:
    build: .
    dockerfile: Dockerfile-prod
    container_name: boilerplate
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    command: npm run start
