export const EXAMPLE_ACTION = 'EXAMPLE_ACTION';
export const EXAMPLE_ACTION_SUCCESS = 'EXAMPLE_ACTION_SUCCESS';
export const EXAMPLE_ACTION_ERROR = 'EXAMPLE_ACTION_FAIL';

// auth
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGIN_FROM_TOKEN = 'LOGIN_FROM_TOKEN';
export const LOGIN_FROM_TOKEN_SUCCESS = 'LOGIN_FROM_TOKEN_SUCCESS';
export const LOGIN_FROM_TOKEN_ERROR = 'LOGIN_FROM_TOKEN_ERROR';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR';

export const LOGOUT = 'LOGOUT';
